import paho.mqtt.client as mqtt
import RPi.GPIO as GPIO     
import time                   

# MQTT topic to receive from
rec_topic="vagutier_ee250_project_1"

# code up to line 44 was generated by chatgbt
# Prompt: Can you provide the code to move two servos? I want one servo to move
# and then the other to move two seconds after
# Servo setup
SERVO1_PIN = 17   #  (GPIO17)
SERVO2_PIN = 18   #  (GPIO18)

GPIO.setmode(GPIO.BCM)           
GPIO.setup(SERVO1_PIN, GPIO.OUT) 
GPIO.setup(SERVO2_PIN, GPIO.OUT) 

pwm1 = GPIO.PWM(SERVO1_PIN, 50)     # (50 Hz)
pwm2 = GPIO.PWM(SERVO2_PIN, 50)

# starting PWN with 0% duty
pwm1.start(0)  
pwm2.start(0)

# converting angle in degrees to duty cycle value
def set_angle(pwm, angle):     
    duty = 2.5 + (angle / 18.0) 
    pwm.ChangeDutyCycle(duty)  
    time.sleep(0.4)            

def move_servos_sequence(): 
    # center both           
    set_angle(pwm1, 90)     
    set_angle(pwm2, 90)     
    time.sleep(1)           

    # move servo 1 then wait 2 sec
    set_angle(pwm1, 0) 
    time.sleep(2)          

    # move servo 2 then wait 2 sec   
    set_angle(pwm2, 0)
    time.sleep(1)     

def on_connect(client, userdata, flags, rc):
    """Subscribes to topic after successful connection"""

    print("Connected to server (i.e., broker) with result code "+str(rc))
    client.subscribe(rec_topic)
   
    #Add the custom callbacks by indicating the topic and the name of the callback handle
    client.message_callback_add(rec_topic, on_action_message)


"""This object (functions are objects!) serves as the default callback for
messages received when another node publishes a message this client is
subscribed to. By "default,"" we mean that this callback is called if a custom
callback has not been registered using paho-mqtt's message_callback_add()."""
def on_message(client, userdata, msg):
    # print("Custom callback  - topic: "+msg.payload.decode())
    print("Default callback - topic: " + msg.topic + "   msg: " + str(msg.payload, "utf-8"))


#Custom message callback.
def on_action_message(client, userdata, message):
   print("Custom callback  - action: "+message.payload.decode())
   print("Action was sent")
   # run servo sequence whenever a message arrives
   move_servos_sequence() 



if __name__ == '__main__':
   
    #create a client object
    client = mqtt.Client()
    #attach a default callback which we defined above for incoming mqtt messages
    client.on_message = on_message
    #attach the on_connect() callback function defined above to the mqtt client
    client.on_connect = on_connect

    """Connect using the following hostname, port, and keepalive interval (in
    seconds). We added "host=", "port=", and "keepalive=" for illustrative
    purposes. You can omit this in python.
       
    The keepalive interval indicates when to send keepalive packets to the
    server in the event no messages have been published from or sent to this
    client. If the connection request is successful, the callback attached to
    `client.on_connect` will be called."""    
    client.connect(host="test.mosquitto.org", port=1883, keepalive=60)


    client.loop_forever()
